In [4]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D
1.0,2.0,x,4
5.5,34,3.4,x
10,x,11.5,8.5
'''
data3=pd.read_csv(StringIO(csv_data))
print(data3.count())
data3.replace("x",np.nan,inplace=True)
print(data3.info())
for x in data3:
    if data3[x].dtype == "object":
        data3[x] = data3[x].astype("float64")
print(data3.info())
print(data3.mean())

A    3
B    3
C    3
D    3
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       2 non-null      object
 2   C       2 non-null      object
 3   D       2 non-null      object
dtypes: float64(1), object(3)
memory usage: 228.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       2 non-null      float64
 2   C       2 non-null      float64
 3   D       2 non-null      float64
dtypes: float64(4)
memory usage: 228.0 bytes
None
A     5.50
B    18.00
C     7.45
D     6.25
dtype: float64

## 丟棄遺失值
+ 您可以使用 dropna 方法再搭配 axis 參數方式進行搭配。
+ 默認情況下，預設為 axis = 0，也就是會沿著 Rows 進行，當發現到任何值為 NA 就會整個 Row 刪除。
+ 若加入參數 how=‘all’ 代表整個 Row 資料都是遺失值情況下才可以刪除丟棄。
+ 加入參數 thresh=N 代表刪除包含少於 N 個觀察值的 row。

In [9]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D,E
2,3,4,5,
6,34,6,
10,,11,8,
,,,
3,,3,,
,5,,,
'''
drop=pd.read_csv(StringIO(csv_data))
print(drop)
drop1 = drop.dropna(axis=0)
print(drop1)
drop2 = drop.dropna(axis=1)
print(drop2)
drop3 = drop.dropna(axis=0,how="all")#全NaN才刪除
print(drop3)

      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
Empty DataFrame
Columns: [A, B, C, D, E]
Index: []
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN

In [18]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D,E
2,3,4,5,
6,34,6,
10,,11,8,
,,,
3,,3,,
,5,,,
'''
drop=pd.read_csv(StringIO(csv_data))
print(drop)
print("====================================")
drop4 = drop.dropna(thresh = 3)#非缺失值(有數值的)<thresh移除 至少要有 thresh 個有效資料才保留
print(drop4)
print("====================================")
drop5 = drop.dropna(subset=["C","D"])# c跟d欄位都不是NaN的保留
print(drop5)
print("====================================")
drop.dropna(thresh=2,inplace=True)
print(drop)

      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
====================================
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
====================================
      A    B     C    D   E
0   2.0  3.0   4.0  5.0 NaN
2  10.0  NaN  11.0  8.0 NaN
====================================
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
4   3.0   NaN   3.0  NaN NaN

## 填充遺失值
+ 可使用 fillna 函數進行填充
  + 輸入要填充的數值
    + 補上中位數：建議補上中位數而非平均值，這樣相對來說不會受到極端值的影響。
    + 根據原本的資料分布補上亂數。
+ 以下兩種方式可以向後或者向前進行填充
   + pad/ffill          代表向後填充
   + bfill/backfill   代表向前填充

In [24]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D,E
2,3,4,5,
6,34,6,
10,,11,8,
,,,
3,,3,,
,5,,,
'''
fill=pd.read_csv(StringIO(csv_data))
print(fill)
fill_zero = fill.fillna(0)
print(fill_zero)
print("=============================")
fill2 = fill.fillna(0,limit=2)#只填上2個0
print(fill2)
print("=============================")
fill3 = fill.ffill()# 如果當前欄位是NaN  向上一筆同欄直到非NaN的值 寫入目前欄位
print(fill3)
print("=============================")
fill4 = fill.bfill()# 如果當前欄位是NaN  向下一筆同欄直到非NaN的值 寫入目前欄位
print(fill4)
print("=============================")

      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
      A     B     C    D    E
0   2.0   3.0   4.0  5.0  0.0
1   6.0  34.0   6.0  0.0  0.0
2  10.0   0.0  11.0  8.0  0.0
3   0.0   0.0   0.0  0.0  0.0
4   3.0   0.0   3.0  0.0  0.0
5   0.0   5.0   0.0  0.0  0.0
=============================
      A     B     C    D    E
0   2.0   3.0   4.0  5.0  0.0
1   6.0  34.0   6.0  0.0  0.0
2  10.0   0.0  11.0  8.0  NaN
3   0.0   0.0   0.0  0.0  NaN
4   3.0   NaN   3.0  NaN  NaN
5   0.0   5.0   0.0  NaN  NaN
=============================
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  5.0 NaN
2  10.0  34.0  11.0  8.0 NaN
3  10.0  34.0  11.0  8.0 NaN
4   3.0  34.0   3.0  8.0 NaN
5   3.0   5.0   3.0  8.0 NaN
=============================
      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  8.0 NaN
2  10.0   5.0  11.0  8.0 NaN
3   3.0   5.0   3.0  NaN NaN
4   3.0   5.0   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
=============================

In [36]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D,E
2,3,4,5,
6,34,6,
10,,11,8,
,,,
3,,3,,
,5,,,
'''
fill=pd.read_csv(StringIO(csv_data))
print(fill)
fillmean1 = fill.mean()
print(fillmean1)
print(type(fillmean1))
print("=======fill================")
for x in fill:
    #print(x,fillmean1[x])
    col_to_fill = fill[x]
    col_to_fill.fillna(fillmean1.loc[x],inplace=True)    
print(fill)

      A     B     C    D   E
0   2.0   3.0   4.0  5.0 NaN
1   6.0  34.0   6.0  NaN NaN
2  10.0   NaN  11.0  8.0 NaN
3   NaN   NaN   NaN  NaN NaN
4   3.0   NaN   3.0  NaN NaN
5   NaN   5.0   NaN  NaN NaN
A     5.25
B    14.00
C     6.00
D     6.50
E      NaN
dtype: float64
<class 'pandas.core.series.Series'>
=======fill================
       A     B     C    D   E
0   2.00   3.0   4.0  5.0 NaN
1   6.00  34.0   6.0  6.5 NaN
2  10.00  14.0  11.0  8.0 NaN
3   5.25  14.0   6.0  6.5 NaN
4   3.00  14.0   3.0  6.5 NaN
5   5.25   5.0   6.0  6.5 NaN

### 檢查重複

In [40]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D
2,3,5,5
5,5,5,5
5,5,5,5
13,23,5,5
'''
df2=pd.read_csv(StringIO(csv_data))
print(df2)
print("-------0---------")
print(df2.duplicated())
print("-------1---------")
print(df2.duplicated("A"))
print("-------2---------")
print(df2.duplicated("D"))

    A   B  C  D
0   2   3  5  5
1   5   5  5  5
2   5   5  5  5
3  13  23  5  5
-------0---------
0    False
1    False
2     True
3    False
dtype: bool
-------1---------
0    False
1    False
2     True
3    False
dtype: bool
-------2---------
0    False
1     True
2     True
3     True
dtype: bool

### 丟棄重複值的資料

In [48]:
import pandas as pd
import  numpy as np
from io import  StringIO
csv_data='''
A,B,C,D
2,3,5,5
5,5,5,5
5,5,5,5
13,23,5,5
'''
df2=pd.read_csv(StringIO(csv_data))
print(df2)
print("===========0================")
print(df2.drop_duplicates(keep="last"))
print("===========1================")
print(df2.drop_duplicates())
print("===========2================")
print(df2.drop_duplicates(keep=False))#不保留
print("===========3================")
print(df2.drop_duplicates(subset=["A","D"],keep=False))#不保留

    A   B  C  D
0   2   3  5  5
1   5   5  5  5
2   5   5  5  5
3  13  23  5  5
===========0================
    A   B  C  D
0   2   3  5  5
2   5   5  5  5
3  13  23  5  5
===========1================
    A   B  C  D
0   2   3  5  5
1   5   5  5  5
3  13  23  5  5
===========2================
    A   B  C  D
0   2   3  5  5
3  13  23  5  5
===========3================
    A   B  C  D
0   2   3  5  5
3  13  23  5  5

## Pand群組

In [51]:
import pandas as pd
import numpy as np
company=["A","B","C"]
data1=pd.DataFrame(
{"company":[company[x] for x in np.random.randint(0,len(company),20)],
"salary":np.random.randint(5,50,20),
"age":np.random.randint(15,50,20)}    
)
print(data1)

   company  salary  age
0        C       8   36
1        C      39   37
2        A      24   19
3        B      32   23
4        A      28   43
5        C      27   40
6        A      44   22
7        B      44   42
8        C       8   21
9        A      26   25
10       C      35   48
11       B      27   44
12       B      45   15
13       C      24   22
14       C      11   32
15       C      16   34
16       A      36   31
17       C      21   27
18       C      37   15
19       A      15   22

In [57]:
group = data1.groupby("company")
print(list(group))

[('A',    company  salary  age
2        A      24   19
4        A      28   43
6        A      44   22
9        A      26   25
16       A      36   31
19       A      15   22), ('B',    company  salary  age
3        B      32   23
7        B      44   42
11       B      27   44
12       B      45   15), ('C',    company  salary  age
0        C       8   36
1        C      39   37
5        C      27   40
8        C       8   21
10       C      35   48
13       C      24   22
14       C      11   32
15       C      16   34
17       C      21   27
18       C      37   15)]

In [60]:
print(group.size())
print(group.sum())
print(group.mean())

company
A     6
B     4
C    10
dtype: int64
         salary  age
company
A           173  162
B           148  124
C           226  312
            salary   age
company
A        28.833333  27.0
B        37.000000  31.0
C        22.600000  31.2

In [61]:
import os
print(os.getcwd())

C:\Users\xvpow\ai_20251229\ch20

In [64]:
import pandas as pd
fortune = pd.read_csv("fortune1000.csv",index_col="Rank",)
print(fortune)
sectors = fortune.groupby("Sector")
print(sectors.size())

                         Company                        Sector  \
Rank
1                        Walmart                     Retailing
2                    Exxon Mobil                        Energy
3                          Apple                    Technology
4             Berkshire Hathaway                    Financials
5                       McKesson                   Health Care
...                          ...                           ...
996   New York Community Bancorp                    Financials
997    Portland General Electric                        Energy
997    Portland General Electric                        Energy
999                      Wendy’s  Hotels, Resturants & Leisure
1000           Briggs & Stratton                   Industrials

                                      Industry           Location  Revenue  \
Rank
1                        General Merchandisers    Bentonville, AR   482130
2                           Petroleum Refining         Irving, TX   246204
3                  Computers, Office Equipment      Cupertino, CA   233715
4     Insurance: Property and Casualty (Stock)          Omaha, NE   210821
5                     Wholesalers: Health Care  San Francisco, CA   181241
...                                        ...                ...      ...
996                           Commercial Banks       Westbury, NY     1902
997                Utilities: Gas and Electric       Portland, OR     1898
997                Utilities: Gas and Electric       Portland, OR     1898
999                              Food Services         Dublin, OH     1896
1000                      Industrial Machinery      Wauwatosa, WI     1895

      Profits  Employees
Rank
1       14694    2300000
2       16150      75600
3       53394     110000
4       24083     331000
5        1476      70400
...       ...        ...
996       -47       3448
997       172       2646
997       172       2646
999       161      21200
1000       46       5480

[1000 rows x 7 columns]
Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

In [69]:
sectors.get_group("Energy").head(10)

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
14,Chevron,Energy,Petroleum Refining,"San Ramon, CA",131118,4587,61500
30,Phillips 66,Energy,Petroleum Refining,"Houston, TX",87169,4227,14000
32,Valero Energy,Energy,Petroleum Refining,"San Antonio, TX",81824,3990,10103
42,Marathon Petroleum,Energy,Petroleum Refining,"Findlay, OH",64566,2852,45440
65,Energy Transfer Equity,Energy,Pipelines,"Dallas, TX",42126,1189,30078
90,ConocoPhillips,Energy,"Mining, Crude-Oil Production","Houston, TX",30935,-4428,15900
95,Exelon,Energy,Utilities: Gas and Electric,"Chicago, IL",29447,2269,29762
98,Tesoro,Energy,Petroleum Refining,"San Antonio, TX",28150,1540,6016
104,Enterprise Products Partners,Energy,Pipelines,"Houston, TX",27028,2521,6800

In [71]:
sectors.sum().head()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,BoeingUnited TechnologiesLockheed MartinGenera...,Aerospace and DefenseAerospace and DefenseAero...,"Chicago, ILFarmington, CTBethesda, MDFalls Chu...",357940,28742,968057
Apparel,NikeVFPVHRalph LaurenHanesbrandsLevi StraussCo...,ApparelApparelApparelApparelApparelApparelAppa...,"Beaverton, ORGreensboro, NCNew York, NYNew Yor...",95968,8236,346397
Business Services,ManpowerGroupOmnicom GroupAramarkVisaWaste Man...,"Temporary HelpAdvertising, marketingDiversifie...","Milwaukee, WINew York, NYPhiladelphia, PAFoste...",272195,28227,1361050
Chemicals,Dow ChemicalDuPontPPG IndustriesMonsantoEcolab...,ChemicalsChemicalsChemicalsChemicalsChemicalsC...,"Midland, MIWilmington, DEPittsburgh, PASt. Lou...",243897,22628,463651
Energy,Exxon MobilChevronPhillips 66Valero EnergyMara...,Petroleum RefiningPetroleum RefiningPetroleum ...,"Irving, TXSan Ramon, CAHouston, TXSan Antonio,...",1517809,-73447,1188927

In [79]:
sectors.sum(numeric_only=True).head()

                     Revenue  Profits  Employees
Sector
Aerospace & Defense   357940    28742     968057
Apparel                95968     8236     346397
Business Services     272195    28227    1361050
Chemicals             243897    22628     463651
Energy               1517809   -73447    1188927

In [78]:
sectors.mean(numeric_only=True).head()

                          Revenue      Profits     Employees
Sector
Aerospace & Defense  17897.000000  1437.100000  48402.850000
Apparel               6397.866667   549.066667  23093.133333
Business Services     5337.156863   553.470588  26687.254902
Chemicals             8129.900000   754.266667  15455.033333
Energy               12441.057377  -602.024590   9745.303279

In [86]:
df_numeric =  fortune.select_dtypes(include="number")#只要數字類型
df_numeric.head()

      Revenue  Profits  Employees
Rank
1      482130    14694    2300000
2      246204    16150      75600
3      233715    53394     110000
4      210821    24083     331000
5      181241     1476      70400

In [87]:
df_numeric = fortune.select_dtypes(exclude="number")
df_numeric.head()#不要數字類型

,Company,Sector,Industry,Location
Rank,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR"
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX"
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA"
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE"
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA"

In [95]:
##sectors 群組
#Employees 最大值
g1 = sectors.get_group("Energy")

Rank
2      75600
14     61500
30     14000
32     10103
42     45440
       ...
981     1040
983      809
995      665
997     2646
997     2646
Name: Employees, Length: 122, dtype: int64